name: tensorflow
channels:
  - defaults
dependencies:
  - _nb_ext_conf=0.4.0=py36_1
  - alabaster=0.7.12=py36_0
  - anaconda-client=1.7.2=py36_0
  - appdirs=1.4.3=py36h28b3542_0
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - astroid=2.0.4=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - automat=0.7.0=py36_0
  - babel=2.6.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - bzip2=1.0.6=h1de35cc_5
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.8.24=py36_1
  - cffi=1.11.5=py36h6174b99_1
  - chardet=3.0.4=py36_1
  - cloudpickle=0.5.6=py36_0
  - clyent=1.2.2=py36_1
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3.1=py36hdbc3d79_0
  - cycler=0.10.0=py36hfc81398_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py36_0
  - docutils=0.14=py36hbfde631_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=h0a44026_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.12=h2098e52_2
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icu=58.2=h4b95b61_1
  - idna=2.7=py36_0
  - imageio=2.4.1=py36_0
  - imagesize=1.1.0=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2019.0=117
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - ipywidgets=7.4.1=py36_0
  - isort=4.3.4=py36_0
  - jasper=2.0.14=h636a363_1
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - jupyter=1.0.0=py36_4
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - keyring=13.2.1=py36_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - lazy-object-proxy=1.3.1=py36h1de35cc_2
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopenblas=0.3.3=hdc02c5d_2
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.2.1=h169cedb_0
  - libpng=1.6.34=he12f830_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=hcb84e12_2
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.8=hab757c2_1
  - markupsafe=1.0=py36h1de35cc_1
  - matplotlib=2.2.2=py36ha7267d0_0
  - mccabe=0.6.1=py36_1
  - mistune=0.8.3=py36h1de35cc_1
  - mkl=2019.0=117
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - nb_anacondacloud=1.4.0=py36_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.1.0=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36h827af21_0
  - nbpresent=3.0.2=py36_1
  - ncurses=6.1=h0a44026_0
  - notebook=5.6.0=py36_0
  - numpy=1.15.1=py36h6a91979_0
  - numpy-base=1.15.1=py36h8a80b8c_0
  - numpydoc=0.8.0=py36_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.0.2p=h1de35cc_0
  - packaging=18.0=py36_0
  - pandas=0.23.0=py36h1702cab_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.1=py36_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pillow=5.3.0=py36hb68e598_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hca0a616_3
  - prometheus_client=0.3.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - psutil=5.4.7=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36h7c891bd_1
  - pyasn1=0.4.4=py36h28b3542_0
  - pyasn1-modules=0.2.2=py36_0
  - pycodestyle=2.4.0=py36_0
  - pycparser=2.18=py36_1
  - pyflakes=2.0.0=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pylint=2.1.1=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_1
  - pyqt=5.9.2=py36h655552a_2
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - python.app=2=py36_9
  - pytz=2018.5=py36_0
  - pyyaml=3.13=py36h1de35cc_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - qt=5.9.6=h45cd832_2
  - qtawesome=0.5.1=py36_1
  - qtconsole=4.4.1=py36_0
  - qtpy=1.5.1=py36_0
  - readline=7.0=h1de35cc_5
  - requests=2.19.1=py36_0
  - rope=0.11.0=py36_0
  - scikit-learn=0.19.1=py36hffbff8c_0
  - scipy=1.1.0=py36hcaad992_0
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36h0a44026_0
  - six=1.11.0=py36_1
  - snowballstemmer=1.2.1=py36h6c7b616_0
  - sphinx=1.8.1=py36_0
  - sphinxcontrib=1.0=py36_1
  - sphinxcontrib-websupport=1.1.0=py36_1
  - spyder=3.3.1=py36_1
  - spyder-kernels=0.2.6=py36_0
  - sqlite=3.24.0=ha441bb4_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36h625a49b_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - twisted=17.5.0=py36_0
  - typed-ast=1.1.0=py36h1de35cc_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - webencodings=0.5.1=py36_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.1=py36_0
  - wrapt=1.10.11=py36h1de35cc_2
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=hf3cbc9b_2
  - zope=1.0=py36_1
  - zope.interface=4.5.0=py36h1de35cc_0
  - pip:
    - absl-py==0.2.2
    - astor==0.6.2
    - gast==0.2.0
    - grpcio==1.12.1
    - markdown==2.6.11
    - protobuf==3.5.2.post1
    - tensorboard==1.8.0
    - tensorflow==1.8.0
    - termcolor==1.1.0
    - werkzeug==0.14.1
prefix: /anaconda3/envs/tensorflow

